CREATE SCHEMA IF NOT EXISTS TEST;
---------------
DROP TABLE IF EXISTS TEST.CENTERS;
DROP TABLE IF EXISTS TEST.LOCATIONS;
DROP TABLE IF EXISTS TEST.CLIENTS;
DROP TABLE IF EXISTS TEST.USERS;
---------------
DROP SEQUENCE IF EXISTS TEST.CENTERS_SEQ;
DROP SEQUENCE IF EXISTS TEST.LOCATIONS_SEQ;
DROP SEQUENCE IF EXISTS TEST.CLIENTS_SEQ;
DROP SEQUENCE IF EXISTS TEST.USERS_SEQ;
---------------
CREATE SEQUENCE TEST.CLIENTS_SEQ START WITH 1000 INCREMENT BY 1;
CREATE TABLE TEST.CLIENTS (
    ID NUMBER(10, 0) PRIMARY KEY,
    NAME VARCHAR2,
    CREATED_DATE DATE DEFAULT NOW(),
    CREATED_BY NUMBER(10, 0),
    MODIFIED_DATE DATE,
    MODIFIED_BY NUMBER(10, 0)
);
---------------
CREATE SEQUENCE TEST.CENTERS_SEQ START WITH 1000 INCREMENT BY 1;
CREATE TABLE TEST.CENTERS (
    ID NUMBER(10, 0) NOT NULL,
    CLIENT_ID NUMBER(10, 0) NOT NULL,
    NAME VARCHAR2,
    ADDRESS VARCHAR2,
    POSTAL_CODE VARCHAR2,
    LOCATION_ID NUMBER(10, 0),
    CREATED_DATE DATE DEFAULT NOW(),
    CREATED_BY NUMBER(10, 0),
    MODIFIED_DATE DATE,
    MODIFIED_BY NUMBER(10, 0),
    CONSTRAINT CLIENT_CENTER_PRIMARY_KEY PRIMARY KEY (ID, CLIENT_ID)
);
---------------
CREATE SEQUENCE TEST.LOCATIONS_SEQ START WITH 1000 INCREMENT BY 1;
CREATE TABLE TEST.LOCATIONS (
    ID NUMBER(10, 0) PRIMARY KEY,
    NAME VARCHAR2,
    CREATED_DATE DATE DEFAULT NOW(),
    CREATED_BY NUMBER(10, 0),
    MODIFIED_DATE DATE,
    MODIFIED_BY NUMBER(10, 0)
);
---------------
CREATE SEQUENCE TEST.USERS_SEQ START WITH 1000 INCREMENT BY 1;
CREATE TABLE TEST.USERS (
    ID NUMBER(10, 0) PRIMARY KEY,
    USERNAME VARCHAR2,
    NAME VARCHAR2,
    SURNAME VARCHAR2,
    ENABLED NUMBER(1, 0),
    PASSWORD_RESET_DATE DATE,
    CREATED_DATE DATE DEFAULT NOW(),
    CREATED_BY NUMBER(10, 0),
    MODIFIED_DATE DATE,
    MODIFIED_BY NUMBER(10, 0)
);