-- Connect to the Pluggable Database (PDB)
ALTER SESSION SET CONTAINER = TESTDB;

-- Drop users if they exist, handling cases where they might not exist yet
BEGIN
    EXECUTE IMMEDIATE 'DROP USER TEST CASCADE';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -1918 THEN
            RAISE;
        END IF;
END;
/

-- Create users
CREATE USER TEST IDENTIFIED BY TEST_PASS;

GRANT CONNECT, RESOURCE, UNLIMITED TABLESPACE, CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE, CREATE TRIGGER TO TEST;

-- Create sequences and tables
BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE TEST.CLIENTS_SEQ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

CREATE SEQUENCE TEST.CLIENTS_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TEST.CLIENTS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE TEST.CLIENTS (
  ID NUMBER(10,0) PRIMARY KEY,
  NAME VARCHAR2(4000),
  CREATED_DATE DATE DEFAULT SYSDATE,
  CREATED_BY NUMBER(10,0),
  MODIFIED_DATE DATE,
  MODIFIED_BY NUMBER(10,0)
);
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE TEST.CENTERS_SEQ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

CREATE SEQUENCE TEST.CENTERS_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TEST.CENTERS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE TEST.CENTERS (
  ID NUMBER(10,0) NOT NULL,
  CLIENT_ID NUMBER(10,0) NOT NULL,
  NAME VARCHAR2(4000),
  ADDRESS VARCHAR2(4000),
  POSTAL_CODE VARCHAR2(4000),
  LOCATION_ID NUMBER(10,0),
  CREATED_DATE DATE DEFAULT SYSDATE,
  CREATED_BY NUMBER(10,0),
  MODIFIED_DATE DATE,
  MODIFIED_BY NUMBER(10,0),
  CONSTRAINT CLIENT_CENTER_PRIMARY_KEY PRIMARY KEY (ID, CLIENT_ID)
);
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE TEST.LOCATIONS_SEQ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

CREATE SEQUENCE TEST.LOCATIONS_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TEST.LOCATIONS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE TEST.LOCATIONS (
  ID NUMBER(10,0) PRIMARY KEY,
  NAME VARCHAR2(4000),
  CREATED_DATE DATE DEFAULT SYSDATE,
  CREATED_BY NUMBER(10,0),
  MODIFIED_DATE DATE,
  MODIFIED_BY NUMBER(10,0)
);
/

INSERT INTO TEST.LOCATIONS (NAME, CREATED_BY)
VALUES ('Test Location', 1);
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE TEST.USERS_SEQ';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN
      RAISE;
    END IF;
END;
/

CREATE SEQUENCE TEST.USERS_SEQ START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE TEST.USERS CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

CREATE TABLE TEST.USERS (
  ID NUMBER(10,0) PRIMARY KEY,
  USERNAME VARCHAR2(4000),
  NAME VARCHAR2(4000),
  SURNAME VARCHAR2(4000),
  ENABLED NUMBER(1,0),
  PASSWORD_RESET_DATE DATE,
  CREATED_DATE DATE DEFAULT SYSDATE,
  CREATED_BY NUMBER(10,0),
  MODIFIED_DATE DATE,
  MODIFIED_BY NUMBER(10,0)
);
/

-- Grant privileges to the user TEST
GRANT ALL PRIVILEGES ON TEST.CENTERS TO TEST;
GRANT ALL PRIVILEGES ON TEST.LOCATIONS TO TEST;
GRANT ALL PRIVILEGES ON TEST.CLIENTS TO TEST;
GRANT ALL PRIVILEGES ON TEST.USERS TO TEST;